- delegate_to: localhost
  vars:
    config_module: "{{ item }}"
  block:
  - set_fact:
      config_template: "{{ lookup('first_found',params,errors='ignore') }}"
    vars:
      params:
        paths: "{{ paths }}"
        files: "{{ paths_templates.files }}"

  - template:
      src: "{{ config_template }}"
      dest: "{{config_dir}}/{{inventory_hostname}}.{{item}}.cfg"
    when: config_template

  - fail:
      msg: >
        Missing configuration template for {{ item }} on device
        {{ netlab_device_type|default(ansible_network_os) }}/{{ ansible_network_os }}
    when: not config_template
